name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest, env: win-x64   }
          - { os: ubuntu-latest,  env: linux-x64 }
          - { os: macos-latest,   env: osx-arm64 }

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install Dependencies
      run: dotnet restore --locked-mode
      
    - name: Build-${{ matrix.os }}
      run: dotnet publish --no-restore -c Release -r ${{matrix.env}} --sc true -p:PublishSingleFile=true -p:PublishAot=true -p:EnableCompressionInSingleFile=true -p:DebugType=none -p:DebugSymbols=false -p:StripSymbols=true -o build/${{matrix.env}}

    - name: Upload-${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: ci-${{ matrix.os }}
        path: build/${{matrix.env}}